name: Snapshot

on: [push, pull_request]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true
          run-install: true

      - name: Build
        run: vp pack

      - name: Create a snapshot version
        id: snapshot
        run: vp dlx pkg-pr-new publish
